// internal/config/seeds_countries.go
package config

import "project-devboard/internal/domain/entities"

func getCountrySeedData() []entities.Country {
    base := entities.BaseEntity{CreatedBy: SystemUserID, LastModifiedBy: SystemUserID}
    return []entities.Country{
        {Id: 1, Name: "Türkiye", FlagCode: "tr", ShortCode: "TR", PhonePrefix: "+90", BaseEntity: base},
        {Id: 2, Name: "United States", FlagCode: "us", ShortCode: "US", PhonePrefix: "+1", BaseEntity: base},
        {Id: 3, Name: "United Kingdom", FlagCode: "gb", ShortCode: "GB", PhonePrefix: "+44", BaseEntity: base},
        {Id: 4, Name: "Germany", FlagCode: "de", ShortCode: "DE", PhonePrefix: "+49", BaseEntity: base},
        {Id: 5, Name: "France", FlagCode: "fr", ShortCode: "FR", PhonePrefix: "+33", BaseEntity: base},
        {Id: 6, Name: "Netherlands", FlagCode: "nl", ShortCode: "NL", PhonePrefix: "+31", BaseEntity: base},
        {Id: 7, Name: "Spain", FlagCode: "es", ShortCode: "ES", PhonePrefix: "+34", BaseEntity: base},
        {Id: 8, Name: "Italy", FlagCode: "it", ShortCode: "IT", PhonePrefix: "+39", BaseEntity: base},
        {Id: 9, Name: "Switzerland", FlagCode: "ch", ShortCode: "CH", PhonePrefix: "+41", BaseEntity: base},
        {Id: 10, Name: "Austria", FlagCode: "at", ShortCode: "AT", PhonePrefix: "+43", BaseEntity: base},
        {Id: 11, Name: "Canada", FlagCode: "ca", ShortCode: "CA", PhonePrefix: "+1", BaseEntity: base},
        {Id: 12, Name: "Australia", FlagCode: "au", ShortCode: "AU", PhonePrefix: "+61", BaseEntity: base},
        {Id: 13, Name: "Japan", FlagCode: "jp", ShortCode: "JP", PhonePrefix: "+81", BaseEntity: base},
        {Id: 14, Name: "South Korea", FlagCode: "kr", ShortCode: "KR", PhonePrefix: "+82", BaseEntity: base},
        {Id: 15, Name: "Brazil", FlagCode: "br", ShortCode: "BR", PhonePrefix: "+55", BaseEntity: base},
        {Id: 16, Name: "Russia", FlagCode: "ru", ShortCode: "RU", PhonePrefix: "+7", BaseEntity: base},
        {Id: 17, Name: "India", FlagCode: "in", ShortCode: "IN", PhonePrefix: "+91", BaseEntity: base},
        {Id: 18, Name: "China", FlagCode: "cn", ShortCode: "CN", PhonePrefix: "+86", BaseEntity: base},
        {Id: 19, Name: "Mexico", FlagCode: "mx", ShortCode: "MX", PhonePrefix: "+52", BaseEntity: base},
        {Id: 20, Name: "Argentina", FlagCode: "ar", ShortCode: "AR", PhonePrefix: "+54", BaseEntity: base},
        {Id: 21, Name: "Sweden", FlagCode: "se", ShortCode: "SE", PhonePrefix: "+46", BaseEntity: base},
        {Id: 22, Name: "Norway", FlagCode: "no", ShortCode: "NO", PhonePrefix: "+47", BaseEntity: base},
        {Id: 23, Name: "Denmark", FlagCode: "dk", ShortCode: "DK", PhonePrefix: "+45", BaseEntity: base},
        {Id: 24, Name: "Finland", FlagCode: "fi", ShortCode: "FI", PhonePrefix: "+358", BaseEntity: base},
        {Id: 25, Name: "Poland", FlagCode: "pl", ShortCode: "PL", PhonePrefix: "+48", BaseEntity: base},
        {Id: 26, Name: "Portugal", FlagCode: "pt", ShortCode: "PT", PhonePrefix: "+351", BaseEntity: base},
        {Id: 27, Name: "Ireland", FlagCode: "ie", ShortCode: "IE", PhonePrefix: "+353", BaseEntity: base},
        {Id: 28, Name: "Belgium", FlagCode: "be", ShortCode: "BE", PhonePrefix: "+32", BaseEntity: base},
        {Id: 29, Name: "Saudi Arabia", FlagCode: "sa", ShortCode: "SA", PhonePrefix: "+966", BaseEntity: base},
        {Id: 30, Name: "United Arab Emirates", FlagCode: "ae", ShortCode: "AE", PhonePrefix: "+971", BaseEntity: base},
        {Id: 31, Name: "Qatar", FlagCode: "qa", ShortCode: "QA", PhonePrefix: "+974", BaseEntity: base},
        {Id: 32, Name: "Kuwait", FlagCode: "kw", ShortCode: "KW", PhonePrefix: "+965", BaseEntity: base},
        {Id: 33, Name: "Egypt", FlagCode: "eg", ShortCode: "EG", PhonePrefix: "+20", BaseEntity: base},
        {Id: 34, Name: "Israel", FlagCode: "il", ShortCode: "IL", PhonePrefix: "+972", BaseEntity: base},
        {Id: 35, Name: "Greece", FlagCode: "gr", ShortCode: "GR", PhonePrefix: "+30", BaseEntity: base},
        {Id: 36, Name: "New Zealand", FlagCode: "nz", ShortCode: "NZ", PhonePrefix: "+64", BaseEntity: base},
        {Id: 37, Name: "Singapore", FlagCode: "sg", ShortCode: "SG", PhonePrefix: "+65", BaseEntity: base},
        {Id: 38, Name: "Hong Kong", FlagCode: "hk", ShortCode: "HK", PhonePrefix: "+852", BaseEntity: base},
        {Id: 39, Name: "Malaysia", FlagCode: "my", ShortCode: "MY", PhonePrefix: "+60", BaseEntity: base},
        {Id: 40, Name: "Thailand", FlagCode: "th", ShortCode: "TH", PhonePrefix: "+66", BaseEntity: base},
        {Id: 41, Name: "Vietnam", FlagCode: "vn", ShortCode: "VN", PhonePrefix: "+84", BaseEntity: base},
        {Id: 42, Name: "Philippines", FlagCode: "ph", ShortCode: "PH", PhonePrefix: "+63", BaseEntity: base},
        {Id: 43, Name: "Indonesia", FlagCode: "id", ShortCode: "ID", PhonePrefix: "+62", BaseEntity: base},
        {Id: 44, Name: "Pakistan", FlagCode: "pk", ShortCode: "PK", PhonePrefix: "+92", BaseEntity: base},
        {Id: 45, Name: "Bangladesh", FlagCode: "bd", ShortCode: "BD", PhonePrefix: "+880", BaseEntity: base},
        {Id: 46, Name: "Ukraine", FlagCode: "ua", ShortCode: "UA", PhonePrefix: "+380", BaseEntity: base},
        {Id: 47, Name: "Romania", FlagCode: "ro", ShortCode: "RO", PhonePrefix: "+40", BaseEntity: base},
        {Id: 48, Name: "Chile", FlagCode: "cl", ShortCode: "CL", PhonePrefix: "+56", BaseEntity: base},
        {Id: 49, Name: "Colombia", FlagCode: "co", ShortCode: "CO", PhonePrefix: "+57", BaseEntity: base},
        {Id: 50, Name: "Peru", FlagCode: "pe", ShortCode: "PE", PhonePrefix: "+51", BaseEntity: base},
		{Id: 51, Name: "Venezuela", FlagCode: "ve", ShortCode: "VE", PhonePrefix: "+58", BaseEntity: base},
		{Id: 52, Name: "Argentina", FlagCode: "ar", ShortCode: "AR", PhonePrefix: "+54", BaseEntity: base},
		{Id: 53, Name: "Ecuador", FlagCode: "ec", ShortCode: "EC", PhonePrefix: "+593", BaseEntity: base},
		{Id: 54, Name: "Bolivia", FlagCode: "bo", ShortCode: "BO", PhonePrefix: "+591", BaseEntity: base},
		{Id: 55, Name: "Paraguay", FlagCode: "py", ShortCode: "PY", PhonePrefix: "+595", BaseEntity: base},
		{Id: 56, Name: "Uruguay", FlagCode: "uy", ShortCode: "UY", PhonePrefix: "+598", BaseEntity: base},
		{Id: 57, Name: "Guyana", FlagCode: "gy", ShortCode: "GY", PhonePrefix: "+592", BaseEntity: base},
		{Id: 58, Name: "Suriname", FlagCode: "sr", ShortCode: "SR", PhonePrefix: "+597", BaseEntity: base},
		{Id: 59, Name: "French Guiana", FlagCode: "gf", ShortCode: "GF", PhonePrefix: "+594", BaseEntity: base},
		{Id: 60, Name: "South Africa", FlagCode: "za", ShortCode: "ZA", PhonePrefix: "+27", BaseEntity: base},
    }
}