// internal/config/seeds_cities.go
package config

import "project-devboard/internal/domain/entities"

func intPtr(i int) *int       { return &i }
func strPtr(s string) *string { return &s }

func getCitySeedData() []entities.City {
    base := entities.BaseEntity{CreatedBy: SystemUserID, LastModifiedBy: SystemUserID}
    tr := intPtr(1) // Türkiye CountryId

    return []entities.City{
        {Id: 1, Name: "Adana", Code: strPtr("01"), DisplayOrder: intPtr(1), CountryId: tr, BaseEntity: base},
        {Id: 2, Name: "Adıyaman", Code: strPtr("02"), DisplayOrder: intPtr(2), CountryId: tr, BaseEntity: base},
        {Id: 3, Name: "Afyonkarahisar", Code: strPtr("03"), DisplayOrder: intPtr(3), CountryId: tr, BaseEntity: base},
        {Id: 4, Name: "Ağrı", Code: strPtr("04"), DisplayOrder: intPtr(4), CountryId: tr, BaseEntity: base},
        {Id: 5, Name: "Amasya", Code: strPtr("05"), DisplayOrder: intPtr(5), CountryId: tr, BaseEntity: base},
        {Id: 6, Name: "Ankara", Code: strPtr("06"), DisplayOrder: intPtr(6), CountryId: tr, BaseEntity: base},
        {Id: 7, Name: "Antalya", Code: strPtr("07"), DisplayOrder: intPtr(7), CountryId: tr, BaseEntity: base},
        {Id: 8, Name: "Artvin", Code: strPtr("08"), DisplayOrder: intPtr(8), CountryId: tr, BaseEntity: base},
        {Id: 9, Name: "Aydın", Code: strPtr("09"), DisplayOrder: intPtr(9), CountryId: tr, BaseEntity: base},
        {Id: 10, Name: "Balıkesir", Code: strPtr("10"), DisplayOrder: intPtr(10), CountryId: tr, BaseEntity: base},
        {Id: 11, Name: "Bilecik", Code: strPtr("11"), DisplayOrder: intPtr(11), CountryId: tr, BaseEntity: base},
        {Id: 12, Name: "Bingöl", Code: strPtr("12"), DisplayOrder: intPtr(12), CountryId: tr, BaseEntity: base},
        {Id: 13, Name: "Bitlis", Code: strPtr("13"), DisplayOrder: intPtr(13), CountryId: tr, BaseEntity: base},
        {Id: 14, Name: "Bolu", Code: strPtr("14"), DisplayOrder: intPtr(14), CountryId: tr, BaseEntity: base},
        {Id: 15, Name: "Burdur", Code: strPtr("15"), DisplayOrder: intPtr(15), CountryId: tr, BaseEntity: base},
        {Id: 16, Name: "Bursa", Code: strPtr("16"), DisplayOrder: intPtr(16), CountryId: tr, BaseEntity: base},
        {Id: 17, Name: "Çanakkale", Code: strPtr("17"), DisplayOrder: intPtr(17), CountryId: tr, BaseEntity: base},
        {Id: 18, Name: "Çankırı", Code: strPtr("18"), DisplayOrder: intPtr(18), CountryId: tr, BaseEntity: base},
        {Id: 19, Name: "Çorum", Code: strPtr("19"), DisplayOrder: intPtr(19), CountryId: tr, BaseEntity: base},
        {Id: 20, Name: "Denizli", Code: strPtr("20"), DisplayOrder: intPtr(20), CountryId: tr, BaseEntity: base},
        {Id: 21, Name: "Diyarbakır", Code: strPtr("21"), DisplayOrder: intPtr(21), CountryId: tr, BaseEntity: base},
        {Id: 22, Name: "Edirne", Code: strPtr("22"), DisplayOrder: intPtr(22), CountryId: tr, BaseEntity: base},
        {Id: 23, Name: "Elazığ", Code: strPtr("23"), DisplayOrder: intPtr(23), CountryId: tr, BaseEntity: base},
        {Id: 24, Name: "Erzincan", Code: strPtr("24"), DisplayOrder: intPtr(24), CountryId: tr, BaseEntity: base},
        {Id: 25, Name: "Erzurum", Code: strPtr("25"), DisplayOrder: intPtr(25), CountryId: tr, BaseEntity: base},
        {Id: 26, Name: "Eskişehir", Code: strPtr("26"), DisplayOrder: intPtr(26), CountryId: tr, BaseEntity: base},
        {Id: 27, Name: "Gaziantep", Code: strPtr("27"), DisplayOrder: intPtr(27), CountryId: tr, BaseEntity: base},
        {Id: 28, Name: "Giresun", Code: strPtr("28"), DisplayOrder: intPtr(28), CountryId: tr, BaseEntity: base},
        {Id: 29, Name: "Gümüşhane", Code: strPtr("29"), DisplayOrder: intPtr(29), CountryId: tr, BaseEntity: base},
        {Id: 30, Name: "Hakkari", Code: strPtr("30"), DisplayOrder: intPtr(30), CountryId: tr, BaseEntity: base},
        {Id: 31, Name: "Hatay", Code: strPtr("31"), DisplayOrder: intPtr(31), CountryId: tr, BaseEntity: base},
        {Id: 32, Name: "Isparta", Code: strPtr("32"), DisplayOrder: intPtr(32), CountryId: tr, BaseEntity: base},
        {Id: 33, Name: "Mersin", Code: strPtr("33"), DisplayOrder: intPtr(33), CountryId: tr, BaseEntity: base},
        {Id: 34, Name: "İstanbul", Code: strPtr("34"), DisplayOrder: intPtr(34), CountryId: tr, BaseEntity: base},
        {Id: 35, Name: "İzmir", Code: strPtr("35"), DisplayOrder: intPtr(35), CountryId: tr, BaseEntity: base},
        {Id: 36, Name: "Kars", Code: strPtr("36"), DisplayOrder: intPtr(36), CountryId: tr, BaseEntity: base},
        {Id: 37, Name: "Kastamonu", Code: strPtr("37"), DisplayOrder: intPtr(37), CountryId: tr, BaseEntity: base},
        {Id: 38, Name: "Kayseri", Code: strPtr("38"), DisplayOrder: intPtr(38), CountryId: tr, BaseEntity: base},
        {Id: 39, Name: "Kırklareli", Code: strPtr("39"), DisplayOrder: intPtr(39), CountryId: tr, BaseEntity: base},
        {Id: 40, Name: "Kırşehir", Code: strPtr("40"), DisplayOrder: intPtr(40), CountryId: tr, BaseEntity: base},
        {Id: 41, Name: "Kocaeli", Code: strPtr("41"), DisplayOrder: intPtr(41), CountryId: tr, BaseEntity: base},
        {Id: 42, Name: "Konya", Code: strPtr("42"), DisplayOrder: intPtr(42), CountryId: tr, BaseEntity: base},
        {Id: 43, Name: "Kütahya", Code: strPtr("43"), DisplayOrder: intPtr(43), CountryId: tr, BaseEntity: base},
        {Id: 44, Name: "Malatya", Code: strPtr("44"), DisplayOrder: intPtr(44), CountryId: tr, BaseEntity: base},
        {Id: 45, Name: "Manisa", Code: strPtr("45"), DisplayOrder: intPtr(45), CountryId: tr, BaseEntity: base},
        {Id: 46, Name: "Kahramanmaraş", Code: strPtr("46"), DisplayOrder: intPtr(46), CountryId: tr, BaseEntity: base},
        {Id: 47, Name: "Mardin", Code: strPtr("47"), DisplayOrder: intPtr(47), CountryId: tr, BaseEntity: base},
        {Id: 48, Name: "Muğla", Code: strPtr("48"), DisplayOrder: intPtr(48), CountryId: tr, BaseEntity: base},
        {Id: 49, Name: "Muş", Code: strPtr("49"), DisplayOrder: intPtr(49), CountryId: tr, BaseEntity: base},
        {Id: 50, Name: "Nevşehir", Code: strPtr("50"), DisplayOrder: intPtr(50), CountryId: tr, BaseEntity: base},
        {Id: 51, Name: "Niğde", Code: strPtr("51"), DisplayOrder: intPtr(51), CountryId: tr, BaseEntity: base},
        {Id: 52, Name: "Ordu", Code: strPtr("52"), DisplayOrder: intPtr(52), CountryId: tr, BaseEntity: base},
        {Id: 53, Name: "Rize", Code: strPtr("53"), DisplayOrder: intPtr(53), CountryId: tr, BaseEntity: base},
        {Id: 54, Name: "Sakarya", Code: strPtr("54"), DisplayOrder: intPtr(54), CountryId: tr, BaseEntity: base},
        {Id: 55, Name: "Samsun", Code: strPtr("55"), DisplayOrder: intPtr(55), CountryId: tr, BaseEntity: base},
        {Id: 56, Name: "Siirt", Code: strPtr("56"), DisplayOrder: intPtr(56), CountryId: tr, BaseEntity: base},
        {Id: 57, Name: "Sinop", Code: strPtr("57"), DisplayOrder: intPtr(57), CountryId: tr, BaseEntity: base},
        {Id: 58, Name: "Sivas", Code: strPtr("58"), DisplayOrder: intPtr(58), CountryId: tr, BaseEntity: base},
        {Id: 59, Name: "Tekirdağ", Code: strPtr("59"), DisplayOrder: intPtr(59), CountryId: tr, BaseEntity: base},
        {Id: 60, Name: "Tokat", Code: strPtr("60"), DisplayOrder: intPtr(60), CountryId: tr, BaseEntity: base},
        {Id: 61, Name: "Trabzon", Code: strPtr("61"), DisplayOrder: intPtr(61), CountryId: tr, BaseEntity: base},
        {Id: 62, Name: "Tunceli", Code: strPtr("62"), DisplayOrder: intPtr(62), CountryId: tr, BaseEntity: base},
        {Id: 63, Name: "Şanlıurfa", Code: strPtr("63"), DisplayOrder: intPtr(63), CountryId: tr, BaseEntity: base},
        {Id: 64, Name: "Uşak", Code: strPtr("64"), DisplayOrder: intPtr(64), CountryId: tr, BaseEntity: base},
        {Id: 65, Name: "Van", Code: strPtr("65"), DisplayOrder: intPtr(65), CountryId: tr, BaseEntity: base},
        {Id: 66, Name: "Yozgat", Code: strPtr("66"), DisplayOrder: intPtr(66), CountryId: tr, BaseEntity: base},
        {Id: 67, Name: "Zonguldak", Code: strPtr("67"), DisplayOrder: intPtr(67), CountryId: tr, BaseEntity: base},
        {Id: 68, Name: "Aksaray", Code: strPtr("68"), DisplayOrder: intPtr(68), CountryId: tr, BaseEntity: base},
        {Id: 69, Name: "Bayburt", Code: strPtr("69"), DisplayOrder: intPtr(69), CountryId: tr, BaseEntity: base},
        {Id: 70, Name: "Karaman", Code: strPtr("70"), DisplayOrder: intPtr(70), CountryId: tr, BaseEntity: base},
        {Id: 71, Name: "Kırıkkale", Code: strPtr("71"), DisplayOrder: intPtr(71), CountryId: tr, BaseEntity: base},
        {Id: 72, Name: "Batman", Code: strPtr("72"), DisplayOrder: intPtr(72), CountryId: tr, BaseEntity: base},
        {Id: 73, Name: "Şırnak", Code: strPtr("73"), DisplayOrder: intPtr(73), CountryId: tr, BaseEntity: base},
        {Id: 74, Name: "Bartın", Code: strPtr("74"), DisplayOrder: intPtr(74), CountryId: tr, BaseEntity: base},
        {Id: 75, Name: "Ardahan", Code: strPtr("75"), DisplayOrder: intPtr(75), CountryId: tr, BaseEntity: base},
        {Id: 76, Name: "Iğdır", Code: strPtr("76"), DisplayOrder: intPtr(76), CountryId: tr, BaseEntity: base},
        {Id: 77, Name: "Yalova", Code: strPtr("77"), DisplayOrder: intPtr(77), CountryId: tr, BaseEntity: base},
        {Id: 78, Name: "Karabük", Code: strPtr("78"), DisplayOrder: intPtr(78), CountryId: tr, BaseEntity: base},
        {Id: 79, Name: "Kilis", Code: strPtr("79"), DisplayOrder: intPtr(79), CountryId: tr, BaseEntity: base},
        {Id: 80, Name: "Osmaniye", Code: strPtr("80"), DisplayOrder: intPtr(80), CountryId: tr, BaseEntity: base},
        {Id: 81, Name: "Düzce", Code: strPtr("81"), DisplayOrder: intPtr(81), CountryId: tr, BaseEntity: base},
    }
}