name: Go CI Pipeline

on:
  push:
    branches: ["develop"]
    paths:
      - "DevBoard.API/**"
      - ".github/workflows/**"

  pull_request:
    branches: ["develop"]
    paths:
      - "DevBoard.API/**"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COVERAGE_THRESHOLD: 70

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DevBoard.API

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install lint tool
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run Lint
        run: golangci-lint run ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint

    defaults:
      run:
        working-directory: DevBoard.API

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Test
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Check Coverage
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | awk '/total/ {print $3}' | sed 's/%//')

          echo "Coverage: $COVERAGE%"

          if [ "$(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l)" -eq 1 ]; then
            echo "Coverage düşük"
            exit 1
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    defaults:
      run:
        working-directory: DevBoard.API

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build binaries
        run: |
          mkdir -p build

          if [ -d "cmd" ]; then
            for d in cmd/*/; do
              [ -d "$d" ] || continue
              name=$(basename "$d")

              echo "Building $name"

              CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
              go build -ldflags="-s -w" -o build/$name ./$d
            done
          else
            go build -ldflags="-s -w" -o build/app .
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-binaries
          path: DevBoard.API/build
