name: Vue CI Pipeline

on:
  pull_request:
    branches: ["develop"]
    paths:
      - "DevBoard.WebUI/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DevBoard.WebUI
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DevBoard.WebUI
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run Tests
        run: npm run test:unit

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DevBoard.WebUI

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Build Project
        run: npm run build

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/bilgisayar-kavramlari-toplulugu/devboard-webui:develop .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/bilgisayar-kavramlari-toplulugu/devboard-webui:develop

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vue-dist
          path: DevBoard.WebUI/dist
