name: Vue CD Pipeline

on:
  push:
    branches:
      - develop
      - eyupsosa34-patch-1

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: devboard-webui

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.image.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lower case repo owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        id: image
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          TAG=${GITHUB_REF_NAME}-${SHORT_SHA}
          IMAGE=${{ env.REGISTRY }}/${OWNER_LC}/${{ env.IMAGE_NAME }}:$TAG
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build -t ${{ steps.image.outputs.image }} ./DevBoard.WebUI

      - name: Push Docker Image
        run: |
          docker push ${{ steps.image.outputs.image }}

      - name: Tag latest per branch
        run: |
          LATEST=${{ env.REGISTRY }}/${OWNER_LC}/${{ env.IMAGE_NAME }}:${GITHUB_REF_NAME}-latest
          docker tag ${{ steps.image.outputs.image }} $LATEST
          docker push $LATEST
