name: Vue CI Pipeline

on:
  push:
    branches: ["develop"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./DevBoard.WebUI

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci --prefer-offline --no-audit
      - run: npm run build

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Image
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE="ghcr.io/${{ github.repository_owner }}/devboard-webui:sha-$SHORT_SHA"

          docker build -t $IMAGE DevBoard.WebUI
          docker push $IMAGE
