name: Vue CD Pipeline

on:
  push:
    branches:
      - develop
      - eyupsosa34-patch-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Sunucuya Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}/devboard || mkdir -p /home/${{ secrets.USERNAME }}/devboard && cd /home/${{ secrets.USERNAME }}/devboard

            # repo yoksa clone, varsa update
            if [ ! -d ".git" ]; then
              git clone https://github.com/Bilgisayar-Kavramlari-Toplulugu/project-devboard.git .
            else
              git pull
            fi

            # eski container temizle
            docker stop devboard || true
            docker rm devboard || true

            # image build
            docker build \
              -t devboard:${{ github.sha }} \
              -f DevBoard.WebUI/Dockerfile \
              DevBoard.WebUI

            # yeni container başlat
            docker run -d \
              --name devboard \
              -p 80:80 \
              devboard:${{ github.sha }}
